version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: navalha_de_ouro_container
    environment:
      POSTGRES_DB: navalhaouro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always